version: "3"

services:

  app:
    build: .
    container_name: codeflix-video-app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "9000"
    environment:
      - _DB_HOST=db
      - _DB_DATABASE=codeflix_videos
      - _DB_USERNAME=root
      - _DB_PASSWORD=root
      - _TEST_DB_DATABASE=codeflix_videos_test
    volumes:
      - .:/var/www:rw,cached
      - ./.docker/php/log:/var/log:rw,cached
    depends_on:
      - db
      - redis
    networks:
      - app-network

  nginx:
    build: ./.docker/nginx
    container_name: codeflix-video-nginx
    entrypoint: ./.docker/nginx/entrypoint.sh
    restart: always
    tty: true
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=app
      - NGINX_PORT=9000
    volumes:
      - .:/var/www
      - ./.docker/nginx/log:/var/log/nginx:rw,cached
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: codeflix-videos-db
    tty: true
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/database/dumps:/dumps:rw,cached
      - ./.docker/database/data:/var/lib/mysql:rw,cached
      - ./.docker/database/config:/etc/mysql/conf.d:rw,cached
      - ./.docker/database/config:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: codeflix-video-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis:/data:rw,cached
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
